# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: minimal
  theme_night:
  font: minimal
  font_size: L

# SEO

marketing:
  seo:
    site_type: Organization
    local_business_type: ''
    org_name: ''
    description: 'Sito di supporto al corso di introduzione a R per i tecnici apistici Unaapi'
    twitter: 'uw_79'
  analytics:
    google_analytics: ''
    google_tag_manager: 'G-V3V7JXQ2Y1'
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

# Site footer

footer:
  copyright:
    notice: 'Â© {year} Unaapi. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: '01/02/06'
  time_format: '15:04'

# Site features

features:
  syntax_highlighter:
    theme_light: github-light
    theme_dark: dracula
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/uvesco/corsoRunaapi/'
    content_dir: content
    branch: main
  comment:
    provider: ''
    disqus:
      shortname: 'corsorunaapi'
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: unaapi
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: false
